# Generated by Django 3.0.1 on 2019-12-28 14:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, verbose_name='詳細資訊')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='accounts.AccountBook', verbose_name='所屬帳簿')),
            ],
            options={
                'unique_together': {('name', 'book')},
            },
        ),
        migrations.CreateModel(
            name='Consume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('is_repay', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, verbose_name='詳細資訊')),
                ('consume_at', models.DateField(default=datetime.date.today, verbose_name='消費日')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consume', to='accounts.AccountBook', verbose_name='所屬帳簿')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.Category', verbose_name='分類')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid', to=settings.AUTH_USER_MODEL, verbose_name='付款人')),
            ],
        ),
        migrations.CreateModel(
            name='Proportion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.PositiveIntegerField(verbose_name='費用')),
                ('consume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list', to='accounts.Consume', verbose_name='消費明細')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percent', to=settings.AUTH_USER_MODEL, verbose_name='付款人')),
            ],
            options={
                'unique_together': {('username', 'consume')},
            },
        ),
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.PositiveIntegerField(choices=[(0, 'creator'), (1, 'writer'), (2, 'reader'), (3, 'leave')], default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='accounts.AccountBook', verbose_name='帳本')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'unique_together': {('user', 'book')},
            },
        ),
    ]
