# Generated by Django 3.0 on 2019-12-20 18:44

import app.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=app.users.models.user_image_path),
        ),
    ]
