# Generated by Django 3.0.1 on 2019-12-21 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile'),
        ('users', '0002_user_image'),
    ]

    operations = [
    ]
