# Generated by Django 3.0.1 on 2019-12-21 08:28

import app.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191221_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=app.users.models.user_image_path),
        ),
    ]
